version: '3.6'

services:
  zookeeper:
    ports:
      - 2181:2181
    container_name: zookeeper
    build: 
      context: .
      dockerfile: zookeeper/dockerfile
    networks:
      - kafka
      - pipes

  server:
    ports:
      - 9092:9092
    container_name: server
    build: 
      context: .
      dockerfile: server/dockerfile
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://server:9092,PLAINTEXT_INTERNAL://server:29092
      KAFKA_CREATE_TOPICS: 'example-topic:1:1'
    networks:
      - kafka

  producer:
    container_name: producer
    networks:
      - pipes
    build: 
      context: .
      dockerfile: producer/dockerfile
    depends_on:
      - zookeeper
      - server

  consumer:
    container_name: consumer
    build: 
      context: .
      dockerfile: consumer/dockerfile
    depends_on:
      - zookeeper
      - server
    networks:
      - pipes


networks:
  kafka:
  pipes: